swap_ec_rw: Support swap from ap
We want to update the AP_RW without changing the version of EC_RW.
However, we don't upload the EC binary when the AP_RW already contains
the EC_RW.

Support extracting EC_RW from one AP binary and swapping into another AP
binary.

BUG=b:388690994
TEST=None
BRANCH=none

Change-Id: If982e80f9f831a902d0c1cf67d7816613cb5d6fd
Signed-off-by: Jian-Jia Su <jjsu@chromium.org>

diff --git a/scripts/image_signing/swap_ec_rw b/scripts/image_signing/swap_ec_rw
--- a/scripts/image_signing/swap_ec_rw
+++ b/scripts/image_signing/swap_ec_rw
@@ -15,6 +15,7 @@ Swap the EC RW (ecrw) within an AP firmware (BIOS) image.
 # Flags.
 DEFINE_string image "" "The AP firmware file (e.g 'image-steelix.bin') to swap out ecrw" i
 DEFINE_string ec "" "The EC firmware file (e.g 'ec.bin')" e
+DEFINE_string ap_for_ec "" "The AP firmware file (e.g 'image-steelix.bin') as source of EC firmware file" a
 
 # Parse command line.
 FLAGS "$@" || exit 1
@@ -30,15 +31,51 @@ CBFS_ECRW_HASH_NAME="ecrw.hash"
 CBFS_ECRW_VERSION_NAME="ecrw.version"
 CBFS_ECRW_CONFIG_NAME="ecrw.config"
 
-swap_ecrw() {
+swap_ecrw_from_ap() {
+  local ap_file=$1
+  local ap_for_ec_file=$2
+  local temp_dir
+  local ecrw_file
+  local ecrw_hash_file
+  local ecrw_version_file
+  local region="${FMAP_REGIONS[0]}"
+  local ecrw_version
+
+  temp_dir=$(mktemp -d)
+  ecrw_file="${temp_dir}/ecrw"
+  cbfstool "${ap_for_ec_file}" extract -r "${region}" -n "${CBFS_ECRW_NAME}" \
+    -f "${ecrw_file}"
+  info "EC RW extracted to ${ecrw_file}"
+
+  ecrw_hash_file="${temp_dir}/ecrw.hash"
+  cbfstool "${ap_for_ec_file}" extract -r "${region}" -n "${CBFS_ECRW_HASH_NAME}" \
+    -f "${ecrw_hash_file}"
+  info "EC RW hash extracted to ${ecrw_hash_file}"
+
+  ecrw_version_file="${temp_dir}/ecrw.version"
+  cbfstool "${ap_for_ec_file}" extract -r "${region}" -n "${CBFS_ECRW_VERSION_NAME}" \
+    -f "${ecrw_version_file}" \
+    || ecrw_version_file="" \
+    && warn "${CBFS_ECRW_VERSION_NAME} not found in source ap file"
+
+  swap_ecrw_in_ap "${ap_file}" "${ecrw_file}" "${ecrw_hash_file}" "${ecrw_version_file}"
+
+  if [[ -n "${ec_version_file}" ]]; then
+    ecrw_version="$(cat "${ec_version_file}")"
+  else
+    ecrw_version="unknown"
+  fi
+  info "${CBFS_ECRW_NAME} (${ecrw_version}) swapped in ${ap_file}"
+  info "Done"
+}
+
+swap_ecrw_from_ec() {
   local ap_file=$1
   local ec_file=$2
   local temp_dir
-  local info
   local ecrw_file
   local ecrw_hash_file
   local ecrw_ver_file
-  local ecrw_comp_type
   local ecrw_ver
   local apro_ver
   local aprw_ver
@@ -54,6 +91,29 @@ swap_ecrw() {
   ecrw_ver_file="${temp_dir}/ecrw.version"
   futility dump_fmap -x "${ec_file}" "RW_FWID:${ecrw_ver_file}" >/dev/null
 
+  swap_ecrw_in_ap "${ap_file}" "${ecrw_file}" "${ecrw_hash_file}" "${ecrw_ver_file}"
+
+  ecrw_ver=$(futility update --manifest -e "${ec_file}" \
+    | jq -r '.default.ec.versions.rw')
+  apro_ver=$(futility update --manifest -i "${ap_file}" \
+    | jq -r '.default.host.versions.ro')
+  aprw_ver=$(futility update --manifest -i "${ap_file}" \
+    | jq -r '.default.host.versions.rw')
+  info "${CBFS_ECRW_NAME} (${ecrw_ver}) swapped in ${ap_file} (RO:${apro_ver}, RW:${aprw_ver})"
+  info "Done"
+  info "Done"
+}
+
+swap_ecrw_in_ap() {
+  local ap_file=$1
+  local ecrw_file=$2
+  local ecrw_hash_file=$3
+  local ecrw_ver_file=$4
+  local region
+  local info
+  local ecrw_comp_type
+  local ecrw_version
+
   for region in "${FMAP_REGIONS[@]}"
   do
     info="$(cbfstool "${ap_file}" print -r "${region}" -k -v \
@@ -64,7 +124,7 @@ swap_ecrw() {
     cbfstool "${ap_file}" remove -r "${region}" -n "${CBFS_ECRW_NAME}"
     cbfstool "${ap_file}" remove -r "${region}" -n "${CBFS_ECRW_HASH_NAME}"
     cbfstool "${ap_file}" remove -r "${region}" -n "${CBFS_ECRW_VERSION_NAME}" \
-      || warn "${CBFS_ECRW_VERSION_NAME} not found, but will be added"
+      || warn "${CBFS_ECRW_VERSION_NAME} not found, but will be added."
     # TODO(b/307788351): Update ecrw.config. Right now the config info cannot
     # be obtained from ec.bin.
     cbfstool "${ap_file}" remove -r "${region}" \
@@ -74,8 +134,12 @@ swap_ecrw() {
       -c "${ecrw_comp_type}" -f "${ecrw_file}" -n "${CBFS_ECRW_NAME}"
     cbfstool "${ap_file}" add -r "${region}" -t raw \
       -c none -f "${ecrw_hash_file}" -n "${CBFS_ECRW_HASH_NAME}"
-    cbfstool "${ap_file}" add -r "${region}" -t raw \
-      -c none -f "${ecrw_ver_file}" -n "${CBFS_ECRW_VERSION_NAME}"
+    if [[ -n "${ecrw_ver_file}" ]]; then
+      cbfstool "${ap_file}" add -r "${region}" -t raw \
+        -c none -f "${ecrw_ver_file}" -n "${CBFS_ECRW_VERSION_NAME}"
+    else
+      warn "${CBFS_ECRW_VERSION_NAME} is missing from source file."
+    fi
   done
 
   local keyset
@@ -85,15 +149,6 @@ swap_ecrw() {
 
   # 'futility sign' will call 'cbfstool truncate' if needed
   futility sign "${ap_file}" --keyset "${keyset}"
-
-  ecrw_ver=$(futility update --manifest -e "${ec_file}" \
-    | jq -r '.default.ec.versions.rw')
-  apro_ver=$(futility update --manifest -i "${ap_file}" \
-    | jq -r '.default.host.versions.ro')
-  aprw_ver=$(futility update --manifest -i "${ap_file}" \
-    | jq -r '.default.host.versions.rw')
-  info "${CBFS_ECRW_NAME} (${ecrw_ver}) swapped in ${ap_file} (RO:${apro_ver}, RW:${aprw_ver})"
-  info "Done"
 }
 
 main() {
@@ -101,12 +156,18 @@ main() {
     flags_help
     die "-i or --image required."
   fi
-  if [[ -z "${FLAGS_ec}" ]]; then
+  if [[ -z "${FLAGS_ec}" ]] && [[ -z "${FLAGS_ap_for_ec}" ]]; then
     flags_help
-    die "-e or --ec required."
+    die "-e or --ec or -b or --ap_for_ec required."
   fi
 
-  swap_ecrw "${FLAGS_image}" "${FLAGS_ec}"
+  if [[ -n "${FLAGS_ec}" ]];then
+    info "walk ec"
+    swap_ecrw_from_ec "${FLAGS_image}" "${FLAGS_ec}"
+  elif [[ -n "${FLAGS_ap_for_ec}" ]]; then
+    info "walk ap"
+    swap_ecrw_from_ap "${FLAGS_image}" "${FLAGS_ap_for_ec}"
+  fi
 }
 
 main "$@"
