swap_ec_rw: Support swap from AP image
For the upcoming firmware release for Android, we want to update the
AP_RW without changing the EC_RW version inside AP_RW. Currently the
swap_ec_rw script only supports getting the EC_RW from an EC image.
Therefore, we would need the EC image (on BCS) with the same version as
the old AP_RW to perform the swap, which is a tedious task.

To simplify the process, support extracting EC_RW from one AP image and
swapping into another AP image.

BUG=b:388690994
TEST=None
BRANCH=none

Change-Id: If982e80f9f831a902d0c1cf67d7816613cb5d6fd
Signed-off-by: Jian-Jia Su <jjsu@chromium.org>

diff --git a/scripts/image_signing/swap_ec_rw b/scripts/image_signing/swap_ec_rw
--- a/scripts/image_signing/swap_ec_rw
+++ b/scripts/image_signing/swap_ec_rw
@@ -16,6 +16,7 @@ Swap the EC RW (ecrw) within an AP firmware (BIOS) image.
 DEFINE_string image "" "The AP firmware file (e.g 'image-steelix.bin') to swap out ecrw" i
 DEFINE_string ec "" "The EC firmware file (e.g 'ec.bin')" e
 DEFINE_string ec_config "" "The EC config file (default is 'ec.config')"
+DEFINE_string ap_for_ec "" "The AP firmware file (e.g 'image-steelix.bin') as source of EC firmware file" a
 
 # Parse command line.
 FLAGS "$@" || exit 1
@@ -31,30 +32,91 @@ CBFS_ECRW_HASH_NAME="ecrw.hash"
 CBFS_ECRW_VERSION_NAME="ecrw.version"
 CBFS_ECRW_CONFIG_NAME="ecrw.config"
 
+extract_ecrw_files_from_ap() {
+  local ecrw_file=$1
+  local ecrw_hash_file=$2
+  local ecrw_ver_file=$3
+  local ecrw_config_file=$4
+  local ap_for_ec_file=$5
+
+  local region="${FMAP_REGIONS[0]}"
+
+  cbfstool "${ap_for_ec_file}" extract -r "${region}" -n "${CBFS_ECRW_NAME}" \
+    -f "${ecrw_file}"
+  info "EC RW extracted to ${ecrw_file}"
+
+  cbfstool "${ap_for_ec_file}" extract -r "${region}" -n "${CBFS_ECRW_HASH_NAME}" \
+    -f "${ecrw_hash_file}"
+  info "EC RW hash extracted to ${ecrw_hash_file}"
+
+  if ! cbfstool "${ap_for_ec_file}" extract -r "${region}" \
+      -n "${CBFS_ECRW_VERSION_NAME}" -f "${ecrw_ver_file}"; then
+    warn "${CBFS_ECRW_VERSION_NAME} not found in source AP file."
+  fi
+
+  if ! cbfstool "${ap_for_ec_file}" extract -r "${region}" \
+      -n "${CBFS_ECRW_CONFIG_NAME}" -f "${ecrw_config_file}"; then
+    warn "${CBFS_ECRW_CONFIG_NAME} not found in source AP file."
+  fi
+}
+
+extract_ecrw_files_from_ec() {
+  local ecrw_file=$1
+  local ecrw_hash_file=$2
+  local ecrw_ver_file=$3
+  local ec_file=$4
+
+  futility dump_fmap -x "${ec_file}" "RW_FW:${ecrw_file}" >/dev/null
+  info "EC RW extracted to ${ecrw_file}"
+
+  openssl dgst -sha256 -binary "${ecrw_file}" > "${ecrw_hash_file}"
+  info "EC RW hash saved to ${ecrw_hash_file}"
+
+  futility dump_fmap -x "${ec_file}" "RW_FWID:${ecrw_ver_file}" >/dev/null
+}
+
 swap_ecrw() {
   local ap_file=$1
   local ec_file=$2
   local ec_config_file=$3
+  local ap_for_ec_file=$4
+
   local temp_dir
-  local info
   local ecrw_file
   local ecrw_hash_file
   local ecrw_ver_file
+
+  local region
+  local info
   local ecrw_comp_type
+
   local ecrw_ver
   local apro_ver
   local aprw_ver
+
   temp_dir=$(mktemp -d)
-  ecrw_file="${temp_dir}/ecrw"
-  futility dump_fmap -x "${ec_file}" "RW_FW:${ecrw_file}" >/dev/null
-  info "EC RW extracted to ${ecrw_file}"
+  ecrw_file="${temp_dir}/${CBFS_ECRW_NAME}"
+  ecrw_hash_file="${temp_dir}/${CBFS_ECRW_HASH_NAME}"
+  ecrw_ver_file="${temp_dir}/${CBFS_ECRW_VERSION_NAME}"
+  ecrw_config_file="${temp_dir}/${CBFS_ECRW_CONFIG_NAME}"
 
-  ecrw_hash_file="${temp_dir}/ecrw.hash"
-  openssl dgst -sha256 -binary "${ecrw_file}" > "${ecrw_hash_file}"
-  info "EC RW hash saved to ${ecrw_hash_file}"
-
-  ecrw_ver_file="${temp_dir}/ecrw.version"
-  futility dump_fmap -x "${ec_file}" "RW_FWID:${ecrw_ver_file}" >/dev/null
+  if [[ -n "${ec_file}" ]]; then
+    extract_ecrw_files_from_ec \
+      "${ecrw_file}" \
+      "${ecrw_hash_file}" \
+      "${ecrw_ver_file}" \
+      "${ec_file}"
+    if [[ -n "${ec_config_file}" ]]; then
+      cp "${ec_config_file}" "${ecrw_config_file}"
+    fi
+  else
+    extract_ecrw_files_from_ap \
+      "${ecrw_file}" \
+      "${ecrw_hash_file}" \
+      "${ecrw_ver_file}" \
+      "${ecrw_config_file}" \
+      "${ap_for_ec_file}"
+  fi
 
   for region in "${FMAP_REGIONS[@]}"
   do
@@ -66,7 +128,7 @@ swap_ecrw() {
     cbfstool "${ap_file}" remove -r "${region}" -n "${CBFS_ECRW_NAME}"
     cbfstool "${ap_file}" remove -r "${region}" -n "${CBFS_ECRW_HASH_NAME}"
     cbfstool "${ap_file}" remove -r "${region}" -n "${CBFS_ECRW_VERSION_NAME}" \
-      || warn "${CBFS_ECRW_VERSION_NAME} not found, but will be added"
+      || true
     cbfstool "${ap_file}" remove -r "${region}" \
       -n "${CBFS_ECRW_CONFIG_NAME}" || true
     cbfstool "${ap_file}" expand -r "${region}"
@@ -74,13 +136,19 @@ swap_ecrw() {
       -c "${ecrw_comp_type}" -f "${ecrw_file}" -n "${CBFS_ECRW_NAME}"
     cbfstool "${ap_file}" add -r "${region}" -t raw \
       -c none -f "${ecrw_hash_file}" -n "${CBFS_ECRW_HASH_NAME}"
-    cbfstool "${ap_file}" add -r "${region}" -t raw \
-      -c none -f "${ecrw_ver_file}" -n "${CBFS_ECRW_VERSION_NAME}"
-    # Add ecrw.config if provided.
-    if [ -n "${ec_config_file}" ] ; then
+    if [[ -e "${ecrw_ver_file}" ]]; then
       cbfstool "${ap_file}" add -r "${region}" -t raw \
-        -c "${ecrw_comp_type}" -f "${ec_config_file}" \
+        -c none -f "${ecrw_ver_file}" -n "${CBFS_ECRW_VERSION_NAME}"
+    else
+      warn "${CBFS_ECRW_VERSION_NAME} is missing from source file."
+    fi
+    # Add ecrw.config if provided.
+    if [[ -e "${ecrw_config_file}" ]]; then
+      cbfstool "${ap_file}" add -r "${region}" -t raw \
+        -c "${ecrw_comp_type}" -f "${ecrw_config_file}" \
         -n "${CBFS_ECRW_CONFIG_NAME}"
+    else
+      warn "${CBFS_ECRW_CONFIG_NAME} is missing from source file."
     fi
   done
 
@@ -92,8 +160,15 @@ swap_ecrw() {
   # 'futility sign' will call 'cbfstool truncate' if needed
   futility sign "${ap_file}" --keyset "${keyset}"
 
-  ecrw_ver=$(futility update --manifest -e "${ec_file}" \
-    | jq -r '.default.ec.versions.rw')
+  if [[ -n "${ec_file}" ]]; then
+    ecrw_ver=$(futility update --manifest -e "${ec_file}" \
+      | jq -r '.default.ec.versions.rw')
+  else
+    # As some old `ap_for_ec_file` image may not have `ecrw_config_file`, use
+    # the `ap_for_ec_file` AP version as the EC RW version.
+    ecrw_ver=$(futility update --manifest -i "${ap_for_ec_file}" \
+      | jq -r '.default.host.versions.ro')
+  fi
   apro_ver=$(futility update --manifest -i "${ap_file}" \
     | jq -r '.default.host.versions.ro')
   aprw_ver=$(futility update --manifest -i "${ap_file}" \
@@ -107,16 +182,16 @@ main() {
     flags_help
     die "-i or --image required."
   fi
-  if [[ -z "${FLAGS_ec}" ]]; then
+  if [[ -z "${FLAGS_ec}" ]] && [[ -z "${FLAGS_ap_for_ec}" ]]; then
     flags_help
-    die "-e or --ec required."
+    die "-e/--ec or -a/--ap_for_ec required."
   fi
   if [[ -z "${FLAGS_ec_config}" ]] && [[ -f "$(dirname ${FLAGS_ec})/ec.config" ]]; then
         FLAGS_ec_config="$(dirname ${FLAGS_ec})/ec.config"
         info "Using ec.config from ${FLAGS_ec_config}"
   fi
 
-  swap_ecrw "${FLAGS_image}" "${FLAGS_ec}" "${FLAGS_ec_config}"
+  swap_ecrw "${FLAGS_image}" "${FLAGS_ec}" "${FLAGS_ec_config}" "${FLAGS_ap_for_ec}"
 }
 
 main "$@"
