swap_ec_rw: Support legacy EC image
The script only supported the Zephyr EC image, which contains the RW_FW
FMAP section, which describes the effective image. However, the legacy
EC image doesn't have the RW_FW section; it only has the EC_RW section,
which describes the allocated slot.

To determine the effective image size, we need to search for and parse
the image_data header.

This change adds support for the legacy EC image. It searches the
cookies within the image_data header, retrieve the image_data.size,
and then truncate the image accordingly.

BUG=b:418274770
TEST=make runtestscripts
BRANCH=none

Change-Id: If9ed8e143fa211f49d36800d47df0ac03e3e9c7f
Signed-off-by: Wai-Hong Tam <waihong@google.com>

diff --git a/scripts/image_signing/swap_ec_rw b/scripts/image_signing/swap_ec_rw
--- a/scripts/image_signing/swap_ec_rw
+++ b/scripts/image_signing/swap_ec_rw
@@ -90,12 +90,60 @@ extract_ecrw_files_from_ap() {
     || warn "${CBFS_ECRW_CONFIG_NAME} not found in source AP file."
 }
 
+# Dump the 32-bit hex string from the given offset in the given EC-RW file.
+read_hex32() {
+  local ecrw_file=$1
+  local offset=$2
+
+  hexdump -n 4 -s "${offset}" -e '1/4 "%08x"' "${ecrw_file}" 2>/dev/null
+}
+
+truncate_ec_rw() {
+    local ecrw_file=$1
+    local offset=0
+    local max_offset=4096
+
+    # Search for the cookies of the image_data header
+    while true; do
+        if [ "${offset}" -gt "${max_offset}" ]; then
+	    die "No image_data's cookies found within ${max_offset} bytes."
+        fi
+
+        cookie1="$(read_hex32 "${ecrw_file}" "${offset}")"
+        if [[ "${cookie1}" == "ce778899" ]]; then
+            local cookie2_offset=$((offset + 44))
+            cookie2="$(read_hex32 "${ecrw_file}" "${cookie2_offset}")"
+            if [ "${cookie2}" == "ceaabbdd" ]; then
+                break
+            fi
+        fi
+        offset=$((offset + 4))
+    done
+
+    # Retrieve image_data.size
+    local size_hex
+    size_hex="$(read_hex32 "${ecrw_file}" $((offset + 36)))"
+    local size_dec
+    size_dec=$((0x${size_hex}))
+    if [[ "$size_dec" -eq 0 ]]; then
+      die "Invalid image size: 0x${size_hex} (${size_dec})."
+    fi
+
+    echo "Found cookies at ${offset}. Image size: 0x${size_hex} (${size_dec})."
+    truncate -s "${size_dec}" "${ecrw_file}"
+    echo "File ${ecrw_file} truncated to ${size_dec} bytes."
+}
+
 extract_ecrw_files_from_ec() {
   local ecrw_file=$1
   local ecrw_ver_file=$2
   local ec_file=$3
 
-  futility dump_fmap -x "${ec_file}" "RW_FW:${ecrw_file}" >/dev/null
+  if ! futility dump_fmap -x "${ec_file}" "RW_FW:${ecrw_file}" >/dev/null ; then
+    info "Falling back to EC_RW section for legacy EC"
+    futility dump_fmap -x "${ec_file}" "EC_RW:${ecrw_file}" >/dev/null
+    truncate_ec_rw "${ecrw_file}"
+  fi
   info "EC RW extracted to ${ecrw_file}"
 
   futility dump_fmap -x "${ec_file}" "RW_FWID:${ecrw_ver_file}" >/dev/null
